server:
  port: 3210

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/photo_app
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: true
    show-sql: true

  application:
    name: liquibase_demo

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml


